
services:
    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - task-network

    mailpit:
        image: axllent/mailpit:latest
        container_name: task-mailpit
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - task-network

volumes:
    mysql_data:

networks:
    task-network:
        driver: bridge
